h5p/h5p-php-library

js/h5p-x-api-event.js
js/h5p-x-api.js

This PR 
* Adds optional completion and success parameters to the setScoredResult method. These can be used to set the statement's result.success and result.completion properties. Completion defaults to true if the parameter is not passed. 
* Makes score and max score optional in case these properties are not relevant for a statement (e.g. maybe only duration and completion are needed). 
This code has not been tested in any way. Is there a recommended way to test H5P code changes? 
Fixes https://github.com/h5p/h5p-php-library/issues/2

Add support for result.success & completion

---

composer.json

Currently the library code is being added to frameworks as a git submodule. This PR would allow installing the library also as a [composer](https://getcomposer.org/) dependency.

Adds minimal composer.json

---

README.txt
doc/spec_en.html
h5p-development.class.php
h5p-event-base.class.php
h5p.classes.php

Spelling corrections, type hints, two unused private methods removed, adjustment to interface for additional missing parameter, method level variable renames to follow pascal case, and a lot lot more. No core logic is changed, I just really hate seeing yellow and red warnings in my IDE.
I also updated docblocks with missing parameters, added docblocks to functions that did not have them

Major clean up of both syntactical errors and spelling

---

h5p-default-storage.class.php
h5p.classes.php

I made these updates:
* In `H5PDefaultStorage::saveExport` an exception is thrown if the export directory can't be created or if the export file can't be written.
* `H5PExport::createExportFile` doesn't silently "eat" the exception, but actually returns FALSE if the file can't be exported.
There were cases before where `H5PExport::createExportFile` could fail and return FALSE, so adding one more case where it can fail and return FALSE doesn't change the semantics of that function. 
There is only one call to `H5PExport::createExportFile`, and that is from `H5PCore::filterParameters`. This call does not check the return value from `H5PExport::createExportFile`. Ideally it should, but currently there is no way `H5PCore::filterParameters` can fail gracefully. Returning FALSE would not make …

don't fail silently in createExportFile

---

styles/h5p.css

There is a bug in iOS with IFrame's that when changing orientation width: 100% stays at landscape rather than going back to portrait. https://bugs.webkit.org/show_bug.cgi?id=155198. Tested on iOS 10 iPhone 7 on image hotspot.

Fixed iOS bug for Image Hotspots and iFrames

---

js/h5p-action-bar.js
styles/h5p.css

This will prevent actionbar buttons from being selectable as described in [HFP-878](https://h5ptechnology.atlassian.net/browse/HFP-878).
Alternatively, the CSS arguments could have been added to the h5p-button class directly, but the class could possibly be used by other elements as well.
Successfully tested with Chrome, IE and Firefox.

Avoid accidently selecting things in the toolbar

---

h5p.classes.php

Adding a non existent file to ZipArchive can lead to archive not being created
http://biostall.com/php-ziparchive-class-not-creating-zip-file-and-no-errors/
error occured on a windows host with iis webserver and php 5.4.4
Using h5p in combination with moodle plugin on moodle 2.8.9

Check for file exists before adding to zip.

---

h5p.classes.php

Some font-family also contains the minus sign (-) in their names and the regex that validates this is missing the minus sign.
e.g. sans-serif

Fixing font-family regex pattern when validating text

---

embed.php

Works in conjunction with modifications to class-h5p-php-admin.php
in the core h5p plugin. Allows other plugins to add code to be
inserted into the head of the embeded iframe generated by embed.php.
See discussion of this issue here:
https://github.com/h5p/h5p-wordpress-plugin/issues/58#issuecomment-337906304

Prints optional additonal head tags in embed.php

---

h5p.classes.php

The "Content-Type" header is capitalized incorrectly. This can lead to unexpected behaviour when parsing responses (e.g. JSON being loaded as strings instead of objects by the JS engine). See https://tools.ietf.org/html/rfc7231#section-3.1.1.5.

BUGFIX: Fix capitalization of the "Content-Type" HTTP header

---

h5p-metadata.class.php

Default language is of type text and should therefore add quotes around the value like source, license and license_version do.

Incorrect json

---

h5p-default-storage.class.php
h5p.classes.php

DIRECTORY_SEPARATOR is not supposed to be used to compose paths; it is supposed to be used with rtrim and other operations on paths handed to you by the system.
All PHP running platforms support '/' as path separator.

Replaced DIRECTORY_SEPARATOR

---

js/h5p-data-view.js
styles/h5p-admin.css

@icc as discussed
If merged in, this pull request will add support for a toggle checkbox in the data view. It will allow to toggle between showing all contents and only the contents of the current user.
This pull request is accompanied by a pull request for the H5P-WordPress plugin: https://github.com/h5p/h5p-wordpress-plugin/pull/98
If you're using the H5P plugin on WordPress with multiple authors, it can become hard to find your own content. If there's no content of the current user on the first page, the current user cannot filter by setting a facet and she/he cannot filter for his/her name because the search field only filters on the content title.
Will try to retrieve user.id, user.name and user.canToggleViewOthersH5PContents from H5PIntegration. If set, allows to show/hide contents …

Add toggler view others contents

---

h5p-development.class.php
h5p.classes.php

The array and string offset access syntax using curly braces is deprecated.
Use $str[$idx] instead of $str{$idx}.
RFC: https://wiki.php.net/rfc/deprecate_curly_braces_array_access

PHP 7.4 fix, don't use curly braces for array/string offset

---

.travis.yml

As mentioned in #68, it would be extremely helpful if a Travis integration were set up to catch PHP incompatibilities before they land.
This pull request just adds an extremely basic .travis.yml which allows for Travis to be integrated to this repository.
This integration just performs a php lint against all versions of PHP that I understand the project to support. 
You can see an example of this job passing at: https://travis-ci.org/andrewnicols/h5p-php-library
It is really easy to set this up at the repository level. Just pop to travis-ci.org, log in, and add the repository. From that point it will be enabled and will run on any incoming pull request and commit.
Sadly there are no unit tests, or functional tests in the repository so I could not add any other tests just yet.

Add Travis for all supported PHP versions

---

.travis.yml
h5p.classes.php

The `find` does not return the exit code from the execed process.
Instead we use `xargs` to execute the php lint which returns a non-zero exit code if any child process failed.

Change lint check to report fails correctly

---

h5p.classes.php

This allows an implementor to choose how the library is served.
This is a replacement for #68 which was reverted recently and which is a requirement for Moodle.

Allow the dependency path to be overridden by child classes

---

h5p.classes.php

It would be great if glTF was included in the default list of whitelisted file extensions so (future) H5P content types may use it to make use of 3D models.
The glTF (Graphics Library Transmission Format) is a common and royalty free JSON based file format for 3D models used in open-source WebGL engines including Three.js (already used within H5P content types) and A-Frame. It's used in a variety of 3D modeling tools, e.g. Blender, Vectary, Autodesk 3ds Max, Autodesk Maya. Please cmp. https://github.com/KhronosGroup/glTF

Add gltf to list of allowed file extensions

---

h5p.classes.php

Currently the metadata fields for `licenseExtras`, `changes.log` and `authorComments` do not consider line breaks to be a valid character for the input value, yet the editor allows to enter line breaks and doesn't filter them out. This doesn't seem to cause trouble when the content isn't shared, but once you download it and try to upload it on any H5P instance (even the same), you'll get notified that those fields are not valid.
When merged in, the metadata fields for `licenseExtras`, `changes.log` and `authorComments` will not consider line breaks to be invalid characters anymore.

HFP-3465 Fix line breaks breaking metadata field validation

---

js/h5p.js

A `resize` has been triggered unconditionally regardless of the state of  `H5P.isFullscreen` for around 7 years :-)

Simplify code

---

js/h5p.js

When embedding h5p and using the fullscreen enter/exit feature, Chrome can produce the following error:
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
at HTMLDocument.<anonymous> 
This happens because arguments.callee is not accessible. To fix this, it is sufficient to name the anonymous callback function and reference it by name.

Fix Chrome fullscreen error

---

styles/h5p-confirmation-dialog.css

When merged in, will not animate the Confirmation Dialog entry/exit if the user has expressed to prefer reduced motion on his/her device. See https://h5ptechnology.atlassian.net/browse/HFP-3815 for details.

HFP-3815 Add reduced motion mode to confirmation dialog

---

js/h5p.js

This should solve the issue where protected vimeo videos can't be used as a src for Interactive Video on iPhone.

AU-7270 Ensure iframe inside h5p iframe sends referer on iPhone

---

styles/h5p.css

When merged in, will add a variant of the fullscreen button that content types can use instead of the regular one.

VA-890 Introduce themed fullscreen button

---

styles/h5p-theme-variables.css

After adding the --h5p-theme-secondary-contrast-cta-hover, now it is working fine.

HFP-4290 Add --h5p-theme-secondary-contrast-cta-hover to theme-variables

---

styles/h5p-theme.css

When merged in will use `--h5p-theme-contrast-cta-white` for the pseudo-element and the header of the reuse dialog big buttons.

VA-1210 Use contrast-cta-white for reuse dialog
